#!/bin/bash 
echo ===========================
start=`date +%s`
echo clearing whitepsace from demos
cd demo
find . -type f \( -name "*.txt" \) -exec perl -p -i -e "s/[ \t]*$//g" {} \;
cd ..
echo removing bin
rm -rf ../bin
mkdir ../bin
echo inlining standalone template
./inline
echo copying files
cp -r * ../bin/
cp .htaccess ../bin/
echo optimizing pngs
rm ../bin/images/*.png
cd images
./minimize 
cd ../
echo optimizing gifs
cd ../bin/documentation/images
./minimize
cd ../../../src
echo removing files
rm -rf ../bin/js/*
rm -rf ../bin/css/*
rm -rf ../bin/tests
rm -rf ../bin/Levels
rm ../bin/compile
rm ../bin/inline
rm ../bin/images/minimize
rm ../bin/documentation/images/minimize
rm ../bin/standalone.html
echo compressing css
cd css
./concat
cd ../
mv css/combined.css ../bin/css/combined.css
java -jar ~/progs/yuicompressor-2.4.8.jar ../bin/css/combined.css > ../bin/css/combined2.css
mv ../bin/css/combined2.css ../bin/css/combined.css
java -jar ~/progs/yuicompressor-2.4.8.jar ../bin/documentation/css/bootstrap.css > ../bin/documentation/css/bootstrap_compressed.css
mv ../bin/documentation/css/bootstrap_compressed.css ../bin/documentation/css/bootstrap.css
echo running google closure compiler
java -jar ~/progs/closure.jar --js_output_file ../bin/js/scripts_compiled.js  \
--js js/Blob.js \
--js js/FileSaver.js \
--js js/jsgif/b64.js \
--js js/jsgif/LZWEncoder.js \
--js js/jsgif/NeuQuant.js \
--js js/jsgif/GIFEncoder.js \
--js js/debug.js \
--js js/globalVariables.js \
--js js/font.js \
--js js/rng.js \
--js js/riffwave.js \
--js js/sfxr.js \
--js js/codemirror/codemirror.js \
--js js/codemirror/active-line.js \
--js js/codemirror/dialog.js \
--js js/codemirror/search.js \
--js js/codemirror/searchcursor.js \
--js js/codemirror/match-highlighter.js \
--js js/codemirror/sublime.js \
--js js/colors.js \
--js js/graphics.js \
--js js/inputoutput.js \
--js js/buildStandalone.js \
--js js/engine.js \
--js js/parser.js \
--js js/editor.js \
--js js/compiler.js \
--js js/console.js \
--js js/soundbar.js \
--js js/toolbar.js \
--js js/addlisteners.js \
--js js/addlisteners_editor.js \
--js js/makegif.js
java -jar ~/progs/closure.jar --js_output_file ../bin/js/scripts_play_compiled.js  \
--js js/globalVariables.js \
--js js/debug_off.js \
--js js/font.js \
--js js/rng.js \
--js js/riffwave.js \
--js js/sfxr.js \
--js js/codemirror.js \
--js js/colors.js \
--js js/graphics.js \
--js js/engine.js \
--js js/parser.js \
--js js/compiler.js \
--js js/inputoutput.js
echo running sed
sed -e 's/<script src="js\/[A-Za-z0-9_\/-]*\.js"><\/script>//g' < editor.html > editor_temp1.html
sed -e 's/<!--TOREPLACE-->/<script src="js\/scripts_compiled.js"><\/script>/g' < editor_temp1.html > editor_temp2.html
sed -e 's/<link rel="stylesheet" href="[A-Za-z0-9_\/-]*\.css">//g' < editor_temp2.html > editor_temp3.html
sed -e 's/<!--CSSREPLACE-->/<link rel="stylesheet" href="css\/combined.css">/' < editor_temp3.html > editor_temp4.html

sed -e 's/<script src="js\/[A-Za-z0-9_\/-]*\.js"><\/script>//g' < play.html > play_temp1.html
sed -e 's/<!--TOREPLACE-->/<script src="js\/scripts_play_compiled.js"><\/script>/g' < play_temp1.html > play_temp2.html

echo copying editor.html over
mv editor_temp4.html ../bin/editor.html
mv play_temp2.html ../bin/play.html
echo compressing html
java -jar ~/progs/htmlcompressor-1.5.3.jar  -r ../bin/ -o ../bin/
echo tidying up
rm editor_temp*.html
rm play_temp*.html
echo gzipping site
cd ../bin
./gzipper
rm gzipper
cd ../src
end=`date +%s`
runtime=$((end-start))
echo script took $runtime seconds
echo ===========================

